import Head from 'next/head'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Authlogin Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
      <div className='bg-slate-400 h-56'>
          Hellow
      </div>
      </>
    </div>
  )
}
